//tealium universal tag - utag.314 ut4.0.202402010709, Copyright 2024 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;u.ev={"view":1,"link":1};u.scriptrequested=u.scriptrequested||false;var TMS=window.TMS;var UDOsAccept=UDOsAccept||['eventType','eventGroup','page_language','page_url','page_name','vid_tealium_visitor_id','vid_adobe_aam_uuid','vid_adobe_mid','vid_customer_id','sid_tealium_session_id','page_category','event_category','event_content','event_action','product_id','product_category','application_id','dom_domain','dom_title','dom_url','tealium_version','tealium_profile','tealium_account','tealium_event','browser_user_agent','browser_height','browser_width','funnel_name','funnel_step_name','funnel_step','campaign_id','tealium_event_uuid','message_id','dom_referrer','vid_adobe_mcvid'];u.map={"_sm_314_1":"eventType","_sm_314_2":"eventGroup","vendor_celebrus_collectionurl":"collection_url,celebrus_collection_url,celebrus_page_url","vendor_celebrus_compact":"compact_version,celebrus_compact_version","vendor_celebrus_packet":"packet_version,celebrus_packet_version","vendor_celebrus_sslport":"sslport,celebrus_sslport","vendor_celebrus_udocollection":"udo_collection","vendor_celebrus_doReinit":"doReinit_collection","vendor_celebrus_doReinit_url_fire":"doReinit_url_fire","vendor_celebrus_csaname":"csa_name","page_url":"page_url","adobe_mcvid":"vid_adobe_mcvid","cp.aam_uuid":"vid_adobe_aam_uuid","application_id":"application_id","qp.cid":"campaign_id","customer_id":"vid_customer_id","event_action":"event_action","event_category":"event_category","event_content":"event_content","funnel_name":"funnel_name","funnel_step":"funnel_step","funnel_step_name":"funnel_step_name","page_category":"page_category","page_language":"page_language","page_name":"page_name","pid_content":"message_id","product_category":"product_category","product_id":"product_id","ut.account":"tealium_account","ut.event":"tealium_event","ut.profile":"tealium_profile","ut.version":"tealium_version","ut.visitor_id":"vid_tealium_visitor_id","dom.viewport_height":"browser_height","dom.viewport_width":"browser_width","dom.domain":"dom_domain","dom.title":"dom_title","dom.referrer":"dom_referrer","dom.url":"dom_url","_sm_314_40":"browser_user_agent","_sm_314_41":"tealium_event_uuid","_sm_314_42":"sid_tealium_session_id","_sm_314_43":"vid_adobe_mid"};u.extend=[function(a,b){try{b['_sm_314_1']="Tealium";}catch(e){utag.DB(e);}
try{b['_sm_314_2']="Scenario";}catch(e){utag.DB(e);}
try{b['_sm_314_40']="browser_user_agent";}catch(e){utag.DB(e);}
try{b['_sm_314_41']="tealium_event_uuid";}catch(e){utag.DB(e);}
try{b['_sm_314_42']="sid_tealium_session_id";}catch(e){utag.DB(e);}
try{b['_sm_314_43']="vid_adobe_mid";}catch(e){utag.DB(e);}},function(a,b){try{if(b['ut.env'].toString().indexOf('dev')>-1){b['vendor_celebrus_collectionurl']='www.isstardev.hsbc.com.ar';b['vendor_celebrus_compact']='3';b['vendor_celebrus_packet']='1';b['vendor_celebrus_sslport']='443';b['vendor_celebrus_doReinit']='1';b['vendor_celebrus_udocollection']='1';b['vendor_celebrus_csaname']='HSBCARDEV';b['vendor_celebrus_doReinit_url_fire']='1'}}catch(e){utag.DB(e);}},function(a,b){try{if(b['ut.env'].toString().indexOf('qa')>-1){b['vendor_celebrus_collectionurl']='www.isstaruat.hsbc.com.ar';b['vendor_celebrus_compact']='3';b['vendor_celebrus_packet']='1';b['vendor_celebrus_sslport']='443';b['vendor_celebrus_doReinit']='1';b['vendor_celebrus_udocollection']='1';b['vendor_celebrus_csaname']='HSBCARUAT';b['vendor_celebrus_doReinit_url_fire']='1'}}catch(e){utag.DB(e);}},function(a,b){try{if(b['ut.env'].toString().indexOf('prod')>-1){b['vendor_celebrus_collectionurl']='www.isstarprod.hsbc.com.ar';b['vendor_celebrus_compact']='3';b['vendor_celebrus_packet']='1';b['vendor_celebrus_sslport']='443';b['vendor_celebrus_doReinit']='1';b['vendor_celebrus_udocollection']='1';b['vendor_celebrus_csaname']='HSBCAR';b['vendor_celebrus_doReinit_url_fire']='1'}}catch(e){utag.DB(e);}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:314");utag.DB(b);var c,d,e,f;u.data={"csa_name":"DEFINED IN EXTENSION","page_url":"","compact_version":"DEFINED IN EXTENSION","packet_version":"DEFINED IN EXTENSION","collection_url":"DEFINED IN EXTENSION","sslport":"443"};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:314:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
utag.DB("send:314:MAPPINGS");utag.DB(u.data);if(!u.data.collection_url){utag.DB(u.id+": Tag not fired: Required attribute not populated [collection_url]");return;}
var csaName=utag.data.vendor_celebrus_csaname=u.data.vendor_celebrus_csaname||u.data.csa_name;var portControl=(TMS.util.check.isDefined(b.vendor_celebrus_sslport)&&b.vendor_celebrus_sslport!="")?":"+u.data.sslport:"";var endpoint="https://"+u.data.collection_url+portControl;(function(u,b){u.data.tealium_event_uuid=(function(s){var str=s||'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx';return str.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=(c=='x')?r:(r&0x3|0x8);return v.toString(16);});})(b.tealium_event_uuid);try{var visitor=(window.s&&window.s.visitor);var orgid=b['adobe_analytics_orgid']||"AE9446FC57CECBEE7F000101";u.data['vid_adobe_mcvid']=b['adobe_mcvid']||(visitor&&visitor['_fields']&&visitor['_fields'].MCMID)||(/(?:\|MCMID\|(\d*)\|)/.exec(utag.data["cp.AMCV_"+orgid+"%40AdobeOrg"])[1])||(visitor&&visitor.getMarketingCloudVisitorID&&visitor.getMarketingCloudVisitorID())
u.data['vid_adobe_mid']=u.data['vid_adobe_mcvid'];}catch(e){}
u.data['tealium_version']=b['ut.version']||TMS.util.getUTVersion();u.data['browser_user_agent']=window.navigator.userAgent.toString()||'';u.data['sid_tealium_session_id']=(b["tealium_visitor_id"]+"_"+b["tealium_session_id"])||'';return u;})(u,b)
if(u.data.udo_collection.toString()!=="1"){try{(function Filter(ar,d){var i,len,mapped=d;for(var s in d){if(d.hasOwnProperty(s)&&TMS.util.check.isDefined(s)){for(i=0,len=ar.length;i<len;i++){if(s==ar[i]){delete mapped[ar[i]];}}}}
return mapped;})(UDOsAccept,u.data)}catch(e){}
}
function mergeUDOs(m,r){var items,e,obj={};for(items in m){if(TMS.util.hasOwn(m,items)){e=m[items].split(",");for(f=0;f<e.length;f++){if((TMS.util.check.isDefined(r[m[items]]))&&(!/vendor\_/.test(items))){obj[e[f]]=r[m[items]];}}}}
return obj;}
if(!u.scriptrequested){window[csaName+'compatVersion']="3";window[csaName+'packetVersion']="1";window[csaName+'useCorsForInitialRequest']="1";window[csaName+'useJsonFormatForInitialCorsRequest']="1";window.CelebrusDataPrivacy={MAY_CONTAIN_PERSONAL_DATA:1,ANONYMOUS_DATA_ONLY:2};window[csaName+'pPO']=function(a,k){window.localStorage&&window.localStorage.setItem(csaName+"P3P",a);var f=new Date;f.setFullYear(f.getFullYear()+20);window[csaName+'SC'](csaName+"P3P="+a,f.toGMTString());k&&window[csaName+'SC'](csaName+"P3P="+a,f.toGMTString(),"","","","",k,!1);"optedOut"==a&&window[csaName+'stopEvents']&&window[csaName+'stopEvents']();window[csaName+'doReInit']?window[csaName+'doReInit']():window[csaName+'Go']&&!window[csaName+'wid']&&[csaName+'Go']()};window[csaName+'optOut']=function(a){window[csaName+'pPO']("optedOut",a)};window[csaName+'optIn']=function(a){window[csaName+'pPO']("optedIn",a)};window[csaName+'anonymous']=function(a){window[csaName+'pPO']("anonymous",a)};function sessionShutdownPeriodExceeded(){var a=!1,a=document.cookie?-1<document.cookie.indexOf(csaName+"SF="):null!=window.sessionStorage.getItem(csaName+"SF");if(!a)return!1;a=window[csaName+'findCookieVal'](csaName+"SF");a=parseInt(a,10);return-1==a||isNaN(a)?!1:Math.abs((new Date).valueOf()-a)>10800000?!0:!1}
function periodicAssessShutdownState(){window[csaName+'findCookieVal'](csaName+"SF")&&(window[csaName+'sessionShutdownPeriodExceeded']()?(window[csaName+'doDeleteCookie']&&window[csaName+'doDeleteCookie'](csaName+"SF"),window[csaName+'lstActv']=(new Date).valueOf(),window[csaName+'qNI']=!0,window[csaName+'findCookieVal'](csaName+"P3P",1),window[csaName+'resetCSA']&&window[csaName+'resetCSA'](),window[csaName+'executeReInitNow']&&window[csaName+'executeReInitNow']()):window.setTimeout(periodicAssessShutdownState,1E4))}
var GL=-1==document.cookie.indexOf(csaName+"SF=")&&-1==document.cookie.indexOf(csaName+"StopFlag=y")&&-2!=window[csaName+'sn'];window[csaName+'pendingManualEvents']||(window[csaName+'pendingManualEvents']=[]);window[csaName+'queuedYoutubeReferences']||(window[csaName+'queuedYoutubeReferences']=[]);window[csaName+'sn']||(window[csaName+'event']=function(a){window[csaName+'pendingManualEvents'].push({eventTypeIdentifier:"basket",payload:a})},window[csaName+'click']=function(a){a&&window[csaName+'pendingManualEvents'].push({eventTypeIdentifier:"click",payload:a})},window[csaName+'textchange']=function(a){a&&window[csaName+'pendingManualEvents'].push({eventTypeIdentifier:"textchange",payload:a})},window[csaName+'formsubmit']=function(a){window[csaName+'pendingManualEvents'].push({eventTypeIdentifier:"formsubmit",payload:a})},window[csaName+'SendJsonData']=function(a,k){window[csaName+'pendingManualEvents'].push({eventTypeIdentifier:"jsondata",payload:a,dataPrivacyVal:k})},window[csaName+'trackYouTubeIframePlayer']=function(a,k){window[csaName+'queuedYoutubeReferences'].push({playerRef:a,playerIdentifier:k})});window[csaName+'initialExecutionCanProceed']=function(){return 1==GL?window[csaName+'windowID']?!1:!0:!1};window[csaName+'blockExecutionForInsertAlreadyPresent']=function(){return window[csaName+'getSD']?!0:!1};window[csaName+'SL']=function(){function a(){l[csaName+'windowID']="_"+(new Date).getTime()+"0."+window[csaName+'generateUUID']()+"_";var m=window[csaName+'findCookieVal'](csaName+"session"),d=window[csaName+'findCookieVal'](csaName+"persisted"),a=window[csaName+'findCookieVal']("usy46gabsosd"),b,f,c,e,k,n=!1,p=!1;a&&(n=!0);m&&(p=!0);var g=m?m.split("_"):null;if(g&&5==g.length)b="x"+g[0]+"_"+g[3],f=g[1],c=g[2],e=g[3],k=g[4],A=e,B=b;else{for(b=""+Math.floor(9999*Math.random()+1);4>b.length;)b="0"+b;a&&(b=A,e=window[csaName+'findCookieVal']("usy46gabsosd"))&&(g=e.lastIndexOf("_"),-1!=g&&(e=e.substring(g+1),b=4==e.length&&e.match(Q)?e:b));A=b;B=l[csaName+'windowID']+A;try{l.top.name||(l.top.name=l[csaName+'windowID'])}catch(r){}
b=B;e=A}
return{sessionInfo:b,lastActivityTS:f,sessionStartTS:c,loadBalancerID:e,sessionKey:k,sessionCookieVal:m,persistedCookieVal:d,legacyCookieVal:a,foundLegacyCookie:n,foundSessionCookie:p}}
function k(){var m=window[csaName+'findCookieVal'](csaName+"persisted");if(m){var d=m.split("_");return 7!=d.length?null:{dbID:d[0],rtID:d[1],udID:d[2],acqTS:d[3],recSN:d[4],recTS:d[5],frq:d[6],cookieVal:m}}
return null}
function f(){if(F){var m="_";F.dbID&&(m=F.dbID+m);F.rtID&&(m+=F.rtID);return m}
return window[csaName+'findCookieVal'](csaName+"DBID",1)}
function e(){return t&&t.sessionKey?t.sessionKey:window[csaName+'findCookieVal'](csaName+"key")}
function c(m){return I?(m=I(m),m=m.replace(/'/g,"%27"),m=m.replace(/~/g,"%7E")):escape(m)}
function p(m){return"https:"==(""+location.protocol).toLowerCase()||1==l[csaName+'ForceSecure']?csaName+"ssl"+m:csaName+"tcp"+m}
function g(m){m=p(m);try{if(l.sessionStorage){var d=l.sessionStorage.getItem(m);if(d)return""+d}}catch(a){}
return""}
function r(m,d){var a=p(m);try{l.sessionStorage&&l.sessionStorage.setItem(a,d)}catch(b){}}
function n(m){try{var d=g(m),a=parseInt(d);return isNaN(a)?0:a}catch(b){return 0}}
function y(){return n("lastQueuePointer")}
function z(m){try{var d=parseInt(g(m));isNaN(d)&&(d=0);49==d?d=0:d++;r(m,""+d)}catch(a){}}
function x(){var m=n("lastProcessPointer"),d=y();m<d&&z("lastProcessPointer")}
function v(){var m=y();g(m)&&z("lastQueuePointer")}
function u(){var m=n("lastProcessPointer"),d="";try{d=g(m)}catch(a){}
try{var f=p(m);try{l.sessionStorage&&l.sessionStorage.removeItem(f)}catch(a){}}catch(a){}
return d}
function w(m){m=m.replace(/&/g,"+");m=m.replace(/%/g,"q");m=m.replace(/(..)(..)/g,"$2$1");m=m.replace(/(........)(.....)/g,"$2$1");var d=f(),a=e();a&&(d+="_"+a);return m="z="+c(d)+"&y="+m}
function J(a,d){return a?-1!==a.indexOf(d,a.length-d.length):!1}
function K(a){function d(){x();b()}
function f(){x();b()}
function b(){var b=u();if(b)
if(0==b.indexOf("reinit:"))d();else{window.CelebrusLoggingUtils&&window.CelebrusLoggingUtils.logEventQueued(b);var c;var e=R;try{var g=endpoint;J(b,":http")&&(g=endpoint);var g=g+"/"+A+"/",b=w(b),k="ZDY21YGC90LI/uw2jde932.bmp?";e&&(k="1"==window[csaName+'useJsonFormatForInitialCorsRequest']?"AEZ32ZHD01MJ/jsEvent.json?":"AEZ32ZHD01MJ/jsEvent.js?");c=g+k+b}catch(n){c=null}
if(c)
if(R)
S(c,d,f);else{null==l[csaName+'sImgArr'][0]&&(l[csaName+'sImgArr'][0]=new Image,b=l[csaName+'sImgArr'][0],b.attachEvent?b.attachEvent("onload",d):b.addEventListener&&b.addEventListener("load",d,!1),b=l[csaName+'sImgArr'][0],e=f,b.attachEvent?b.attachEvent("onerror",e):b.addEventListener&&b.addEventListener("error",e,!1));try{l[csaName+'sImgArr'][0].src=c}catch(n){f()}}
else f()}
else a()}
l[csaName+'sImgArr']=[];b()}
function G(a,d,f,b){return(d=window[csaName+'findCookieVal'](a))?a+"="+d:""}
function L(a,d){""!=d&&(""!=a&&(a+="; "),a+=d);return a}
function S(a,d,f){var b=a.indexOf("?"),c="",e="";-1==b?c=a:(c=a.substring(0,b),e=a.substring(b+1));var g=new XMLHttpRequest;g.open("POST",c,!0);g.withCredentials=!0;g.setRequestHeader("Content-Type","text/plain;charset=UTF-8");d&&(g.onload=function(){d(g)});f&&(g.onerror=function(){f(g)});try{g.send(e)}catch(k){}}
if(!window[csaName+'blockExecutionForInsertAlreadyPresent']()){var l=window,D=document,U=location,T=D.cookie,A="",B="",Q=/^[a-z0-9]+$/i;l[csaName+'LF']=!0;l[csaName+'TCP']=endpoint;l[csaName+'SSL']=endpoint;l[csaName+'gPr']=function(a){var d=(""+U.protocol).toLowerCase();if("https:"==d)return endpoint;a||(a=d);1==l[csaName+'ForceSecure']&&(a="https:");return"http:"==a||"http"==a?endpoint:endpoint};window[csaName+'clearStoppedState']=function(){window[csaName+'doDeleteCookie']&&window[csaName+'doDeleteCookie'](csaName+"SF")};window[csaName+'stop']=function(){window[csaName+'deleteSessionCookie']&&window[csaName+'deleteSessionCookie']();if(document.cookie)window[csaName+'SC']&&window[csaName+'doDeleteCookie'](csaName+"key");else try{window.sessionStorage&&window.sessionStorage.removeItem(csaName+"key")}catch(a){}
window[csaName+'oTP']=!1;window[csaName+'SC']&&window[csaName+'SC'](csaName+"SF="+(new Date).valueOf())};var I=l.encodeURIComponent,t="",F="";window[csaName+'cookieList']=[];l[csaName+'gC']=function(a){var d=("usy46gabsosd "+csaName+"uvt "+csaName+"DBID "+csaName+"key "+csaName+"session "+csaName+"persisted "+csaName+"P3P").split(" "),f="";if(true){for(var b=document.cookie,c=0;c<d.length;c++){var e=G(d[c],a);e&&(f=L(f,e),b=-1<b.indexOf(e+"; ")?b.replace(e+"; ",""):-1<b.indexOf(e+";")?b.replace(e+";",""):b.replace(e,""))}
return{celebrusCookies:f,siteCookies:b}}
d=("usy46gabsosd "+csaName+"uvt "+csaName+"DBID "+csaName+"key "+csaName+"session "+csaName+"persisted "+csaName+"P3P").split(" ");for(c=0;c<d.length;c++)
(e=G(d[c],a))&&(f=L(f,e));d="";if(0<window[csaName+'cookieList'].length)
for(b=0,c=window[csaName+'cookieList'].length;b<c;b++)
(e=G(window[csaName+'cookieList'][b],a))&&(d=L(d,e));return{celebrusCookies:f,siteCookies:d}};l[csaName+'ae']=function(){l[csaName+'wid']||((new Date).valueOf()-l[csaName+'Tm']>30000?0===l.frames.length&&window[csaName+'doDeleteCookie']&&(window[csaName+'doDeleteCookie']("usy46gabsosd"),window[csaName+'doDeleteCookie'](csaName+"session"),l[csaName+'SC'](csaName+"SF="+(new Date).valueOf()),periodicAssessShutdownState()):l.setTimeout(l[csaName+'ae'],2E3))};l[csaName+'client_event']=function(a,d){if(!(-1<document.cookie.indexOf(csaName+"SF="))){var c=window;c[csaName+'queueUserEvent']?c[csaName+'queueUserEvent'](a,d):c.setTimeout(window[csaName+'client_event']('"'+a+'"','"'+d+'"'),500)}};l[csaName+'GP']=function(a){return null};l[csaName+'GPWID']=function(a){return a[csaName+'windowID']};l[csaName+'executeJsonResponse']=function(a,d){var c=a,b=window[csaName+'wid'];d||(c=JSON.parse(a));var f=c.windowVariables,e;for(e in f)0===e.indexOf(csaName)&&(window[e]=csaName+"uSC"==e||csaName+"useCors"==e||csaName+"doCapture"==e||csaName+"lookups"==e||csaName+"useJsonFormatRequest"==e?"true"==f[e]:csaName+"idl"==e||csaName+"sST"==e||csaName+"mST"==e?parseInt(f[e],10):f[e]);if(f=c.queueNavigatorInfo)window[csaName+'qNI']=f;if(c.isExcludedFromSample&&setShutdown)setShutdown();else{(f=c.isMinimalCookieFormat)?(window[csaName+'deleteLegacyCookies']&&window[csaName+'deleteLegacyCookies'](),sessionset(c.sessionCookieValue)):(legacyset(c.sn,c.lastActivityTs,c.sessionStartTs,c.lbId),keyset(c.sessionKey));window[csaName+'doCelebrusInsertInvocation']&&window[csaName+'doCelebrusInsertInvocation'](b);if(b=c.persistedCookieValues)f?persisted(b.dbID,b.rtId,b.acq,b.sn,b.cookieName,b.cookieExpiry,b.frq,b.acqTS,b.recTS,b.trackDevices):(b.trackDevices?uvt(b.acq,b.sn,b.cookieExpiry,b.acqTS,b.recTS):window[csaName+'doDeleteCookie']&&window[csaName+'doDeleteCookie'](csaName+"uvt"),window[csaName+'doDeleteCookie']&&window[csaName+'doDeleteCookie'](csaName+"DBID"),DBIDset(c.dbID+"_"+c.rtId,c.cookieExpiry));if(c.contentResponse&&window[csaName+'RTEHandler']){b=[];try{b=JSON.parse(c.contentResponse)}catch(g){}
try{window[csaName+'RTEHandler'].handleResponse(b)}catch(g){}}}};l[csaName+'dynamicCreateScript']=function(a,d,c){var b=document;if(b.getElementById){var e=b.getElementsByTagName("head").item(0);e&&(b=b.createElement("SCRIPT"),b.type="text/javascript",b.id=a,d&&(b.src=d),c&&(b.text=c),e.appendChild(b))}};l[csaName+'LC']=function(a,d){csaName+"csaId"!=d&&window[csaName+'isCorsPermitted']()?S(a,function(a){200===a.status&&(a=a.responseText,window[csaName+'isCorsPermitted']()&&"1"==window[csaName+'useJsonFormatForInitialCorsRequest']?a&&window[csaName+'executeJsonResponse'](a):window[csaName+'dynamicCreateScript'](d,"",a))},null):window[csaName+'dynamicCreateScript'](d,a,"")};window[csaName+'isCorsPermitted']=function(){if("function"==typeof XMLHttpRequest||"object"==typeof XMLHttpRequest){var a=new XMLHttpRequest;return"1"==window[csaName+'useCorsForInitialRequest']&&"withCredentials"in a}
return!1};var R=window.sessionStorage&&window[csaName+'isCorsPermitted']();l[csaName+'GP']=function(a){try{return a===a.parent?null:a.parent}catch(d){}
return null};l[csaName+'TWID']="AUTOSET";window[csaName+'resetCSA']=function(){window[csaName+'doResetCSA']&&window[csaName+'doResetCSA']()};window[csaName+'doReInit']=function(a){try{var d=window.sessionStorage?!0:!1;d&&window[csaName+'sessionStorageEnabled']&&(d=window[csaName+'sessionStorageEnabled']());if(d&&window[csaName+'oTP']){v();var c=y(),d="",d=g(c);d||(r(c,"reinit:"+window[csaName+'windowID']+(a?":1":":0")),v())}else window[csaName+'executeReInitNow']&&window[csaName+'executeReInitNow']()}catch(b){}};window[csaName+'executeReInitNow']=function(a){window[csaName+'clearStoppedState']&&window[csaName+'clearStoppedState']();l[csaName+'lstActv']=(new Date).valueOf();window[csaName+'findCookieVal'](csaName+"P3P",1);window[csaName+'resetCSA']&&window[csaName+'resetCSA']();a&&(window[csaName+'deleteSessionCookie']&&window[csaName+'deleteSessionCookie'](),v());if(window[csaName+'AppBridgeV2']){window[csaName+'awaitingAppResponse']=!0;try{var d=window[csaName+'findCookieVal'](csaName+"persisted");window[csaName+'AppBridgeV2'].requestSessionInformation(location.href,d,window[csaName+'windowId'],!0)}catch(c){window[csaName+'appSessionObject']="",window[csaName+'awaitingAppResponse']=!1,window[csaName+'getSD']&&window[csaName+'getSD'](document.body,window,document,navigator)}}else window[csaName+'getSD']&&window[csaName+'getSD'](document.body,window,document,navigator)};window[csaName+'tmoPoll']=function(){var a=l[csaName+'lstActv'],d=l[csaName+'idl'],c=(new Date).valueOf();-1!=a&&c-a>d&&window[csaName+'doReInit']&&window[csaName+'doReInit']();window.setTimeout(window[csaName+'tmoPoll'],1E4)};0===window.location.href.indexOf("file://")&&window[csaName+'tmoPoll']();window[csaName+'jsInsertAlreadyLoaded']=!1;l[csaName+'getSD']=function(g,d,n){function b(a,h,b){if(!h&&0!==h&&!1!==h)return b;h=c(h);b.length+a.length+h.length<=E&&(b=b+a+h);return b}
function l(a,h,b,d,c,e,f){return a.length+b.length+d.length+c.length+h.length+e.length+f.length+3+20<=E?!0:!1}
function p(a,h){try{a||(a="");var b=a.split("_");if(5>b.length){var d=(new Date).valueOf();return h.sessionNumber+"_"+d+"_"+d+"_"+h.loadBalancerId+"_"+h.sessionKey}
b[0]=h.sessionNumber;b[3]=h.loadBalancerId;b[4]=h.sessionKey;return b.join("_")}catch(c){return a}}
function r(a,b){return b&&b.uvt?b.uvt:""}
function y(a){var h="",h=window[csaName+'isCorsPermitted']()&&"1"==window[csaName+'useJsonFormatForInitialCorsRequest']?""+a+"/"+A+"/handler9/session.json?":""+a+"/"+A+"/handler9/session.js?";a=e();window[csaName+'appSessionObject']?((a=window[csaName+'appSessionObject'])&&t&&(t.sessionInfo="x"+a.sessionNumber+"_"+a.loadBalancerId,t.loadBalancerID=a.loadBalancerId,t.sessionKey=a.sessionKey,t.sessionCookieVal=p(t.sessionCookieVal,a),persistedValFromAppComponents=r(t.persistedCookieVal,a).split("="),2==persistedValFromAppComponents.length&&(t.persistedCookieVal=persistedValFromAppComponents[1]),A=t.loadBalancerID,B=t.sessionInfo),h=b("se=",t.sessionInfo,h),h=b("&wf=",t.sessionCookieVal,h),h=b("&wg=",t.persistedCookieVal,h),h=b("&tz=",t.sessionKey,h)):(h=t&&t.foundSessionCookie&&!t.foundLegacyCookie?b("se=",t.sessionInfo,h):b("se=",B,h),h=b("&wf=",t.sessionCookieVal,h),h=b("&wg=",t.persistedCookieVal,h),h=b("&di=",f(),h),h=b("&tz=",a,h));var g=window[csaName+'consent'],h=b("&us=",g,h),h=b("&sj=",csaName,h),h=b("&aP=",d[csaName+'windowID'],h),h=b("&bd=",navigator.cookieEnabled,h),h=b("&si=",navigator.javaEnabled(),h),h=b("&aM=",Q(d),h);a=L();-2<a&&(h=b("&aO=",""+a,h));h=b("&vb=",d[csaName+'compatVersion'],h);h=b("&wa=","8.20.20226",h);try{h=d.top.name?b("&aW=",d.top.name,h):b("&aW=",d[csaName+'windowID'],h)}catch(m){}
a="not_available";try{a=d==d.top}catch(m){}
h=b("&bu=",a,h);a=d[csaName+'gC'](T);if(window[csaName+'appSessionObject']){for(var q=a.celebrusCookies.split("; "),k=!1,u=!1,x=!1,v=0,V=q.length;v<V;v++){var w=q[v].split("=");2==w.length&&(csaName+"session"==w[0]||"usy46gabsosd"==w[0]?(q[v]=csaName+"session="+p(w[1],window[csaName+'appSessionObject']),k=!0):csaName+"persisted"==w[0]?(q[v]=r(w[1],window[csaName+'appSessionObject']),u=!0):csaName+"P3P"==w[0]&&(q[v]=csaName+"P3P="+g,x=!0))}
k||(q[q.length]=p("",window[csaName+'appSessionObject']));u||(q[q.length]=r("",window[csaName+'appSessionObject']));x||(q[q.length]=csaName+"P3P="+g);g=q.join("; ");a.celebrusCookies=g}
k=a.siteCookies;g=c(a.celebrusCookies);if(h.length<E){q=[];q[0]=n.title;q[1]=k;q[2]=n.referrer;q[3]=location.href;(q[4]=d[csaName+'PageID'])||0===d[csaName+'PageID']||(q[4]="");for(u=k=!1;!l(h,c(q[0]),c(q[1]),c(q[2]),c(q[3]),c(q[4]),g)&&!k;)k=0,c(q[1]).length>c(q[k]).length&&(k=1),c(q[2]).length>c(q[k]).length&&(k=2),c(q[3]).length>c(q[k]).length&&(k=3),c(q[4]).length>c(q[k]).length&&(k=4),q[k]=q[k].substring(0,Math.min(q[k].length/2,E-h.length-20)),u=!0,k=0===q[0].length&&0===q[1].length&&0===q[2].length&&0===q[3].length&&0===q[4].length;h=b("&cf=",q[0],h);h=b("&az=",a.celebrusCookies+"; "+q[1],h);h=b("&ar=",q[2],h);h=b("&au=",q[3],h);h=b("&sg=",q[4],h);u&&(h=b("&ic=","true",h))}
return h}
function v(){for(var a=u(),b=0;a&&50>b;)
if(0==a.indexOf("reinit:"))a=u(),b++;else return a;return null}
function z(){var a,b;if(b=v()){J(b,":https")&&!H&&(H=!0,C=N);x();a="";for(var d=0;b&&50>d;){a="";for(var c=w(b),e=0;b&&a.length+c.length<E&&50>e;)a=a+c+"&a=2",b=v(),J(b,":https")&&!H&&(H=!0,C=N),b&&(x(),c=w(b)),e++;b&&(c=endpoint,H||(c=endpoint),resourcePath="1"==window[csaName+'useJsonFormatForInitialCorsRequest']?"/AEZ32ZHD01MJ/jsEvent.json?":"/AEZ32ZHD01MJ/jsEvent.js?",c=c+resourcePath+"z="+a.substring(4),S(c));d++}
window[csaName+'LC'](C+
"&ipe="+a,csaName+"loadPageId")}else window[csaName+'LC'](C,csaName+"loadPageId")}
function G(a,b,c,e,f,g,k,m){D=window[csaName+'gPr']();(a=n.cookie)||(a="");if(""==a&&window.sessionStorage){try{(a=window.sessionStorage.getItem("usy46gabsosd"))||(a="");c=b="";window.localStorage&&(b=window.localStorage.getItem(csaName+"DBID"),c=window.localStorage.getItem(csaName+"uvt"));var l=window.sessionStorage.getItem(csaName+"key");a=a?"usy46gabsosd="+a:"";b&&(a+="; "+csaName+"DBID="+b);c&&(a+="; "+csaName+"uvt="+c);l&&(a+="; "+csaName+"key="+l)}catch(p){}
T=a}
a.length>O&&a.substring(0,O);if(t.foundLegacyCookie||t.foundSessionCookie)t.foundLegacyCookie&&!t.sessionCookieVal&&(b=a.indexOf("usy46gabsosd"),l=a.indexOf(";",b),-1==l&&(l=a.length),l=a.substring(b,l),c=csaName+"__",e=l.indexOf(c),-1<e?(b=l.indexOf("::",e),0>b&&(b=l.indexOf(";",e)),0>b&&(b=l.length),B="x"+l.substring(e+c.length,b)):(c=csaName+"_",e=l.indexOf(c),-1<e?(e+=c.length-1,b=l.indexOf("::",e),0>b&&(b=l.indexOf(";",e)),0>b&&(b=l.length),B=l.substring(e,b)):(l=a.indexOf("usy46gabsosd="),b=a.indexOf(";",l),0>b&&(b=a.length),B=d[csaName+'windowID']+A,d[csaName+'SC'](a.substring(l,b)+"::"+csaName+d[csaName+'windowID']+A))));else{d[csaName+'SC']("usy46gabsosd="+csaName+d[csaName+'windowID']+A);B=d[csaName+'windowID']+A;try{d.top.name||(d.top.name=d[csaName+'windowID'])}catch(p){}}
I=y(endpoint);N=y(endpoint);C=H?N:I;!d[csaName+'SF']&&C.length<=E&&(window.CelebrusLoggingUtils&&window.CelebrusLoggingUtils.logConfigurationSent(C),window[csaName+'isCorsPermitted']()?window[csaName+'sendScriptRequests'](C,D,z,window[csaName+'processAppResponse']):window[csaName+'sendScriptRequests'](C,D,"",window[csaName+'processAppResponse']));d[csaName+'ae']()}
function L(a,b,c){if(P){a=P(d);try{if(!a||!a.frames)return-1;b=a.frames;for(c=0;c<b.length;c++)
if(b[c]==d)return c}catch(e){}}
return-1}
t=a();F=k();var E=1940,O=1024,C="",D="",N="",I="";window[csaName+'isCorsPermitted']()&&(E=51200,O*=4);g=window;var M;M=window[csaName+'appSessionObject']&&window[csaName+'appConsent']?window[csaName+'appConsent']:window[csaName+'findCookieVal'](csaName+"P3P",1);g[csaName+'consent']=M;var H=endpoint==window[csaName+'gPr']();window[csaName+'processAppResponse']=function(a,b,c,d){if(d!=window[csaName+'windowId'])
for(var e=window.frames,f=0;f<e.length;f++)try{e[f].window[csaName+'processAppResponse']&&e[f].window[csaName+'processAppResponse'](a,b,c,d)}catch(g){}else window[csaName+'isCorsPermitted']()&&"1"==window[csaName+'useJsonFormatForInitialCorsRequest']?a&&window[csaName+'executeJsonResponse'](a,c):window[csaName+'dynamicCreateScript'](b,"",a)};d[csaName+'GPWID']=function(a,b){if(!P)return"not_available";(b=P(a))||(b=a);try{return b[csaName+'windowID']}catch(c){return"not_available"}};var P=d[csaName+'GP'],Q=d[csaName+'GPWID'];d[csaName+'Tm']=(new Date).valueOf();R?G():K(G)};var M=window[csaName+'initialExecutionCanProceed']();!M&&window[csaName+'findCookieVal'](csaName+"SF")?window[csaName+'periodicAssessShutdownState']():(M||window.SpeedTrapComponent)&&l[csaName+'getSD'](D.body,l,D)}};window[csaName+'sendScriptRequests']=function(a,k,f,e){window.CelebrusLoggingUtils&&window.CelebrusLoggingUtils.isDryRun()?window.CelebrusLoggingUtils.executeResponseForDryRun():(window.sessionStorage&&f?f():window[csaName+'LC'](a,csaName+"loadPageId"),window[csaName+'jsInsertAlreadyLoaded']||(window[csaName+'LC'](""+k+"/JavascriptInsert.js",csaName+"csaId"),window[csaName+'jsInsertAlreadyLoaded']=!0))};window[csaName+'cookieAllowsScriptToProceed']=function(a){return-1<a.indexOf(csaName+"SF=")?!1:!0};function Start(){function a(a){k&&(window[csaName+'SL']&&window[csaName+'SL'](),k=!1)}
var k=!1;"prerender"==document.webkitVisibilityState||document.hidden?(k=!0,document.addEventListener&&(document.addEventListener("webkitvisibilitychange",a,!1),document.addEventListener("visibilitychange",a,!1))):window[csaName+'SL']&&window[csaName+'SL']()}
window[csaName+'onInitialSessionInformationResponse']=function(a,k,f){if(f!=window[csaName+'windowId']){for(var e=window.frames,c=0;c<e.length;c++)try{if(e[c].window[csaName+'onInitialSessionInformationResponse']&&e[c].window[csaName+'onInitialSessionInformationResponse'](a,k,f))return!0}catch(p){}
return!1}
try{e=window[csaName+'awaitingAppResponse']=!1;f="";if(a){try{f=JSON.parse(a)}catch(p){}
f&&(window[csaName+'appSessionObject']&&(f.sessionNumber!=window[csaName+'appSessionObject'].sessionNumber||window[csaName+'wid'])&&(e=!0),window[csaName+'appSessionObject']=f)}
window[csaName+'appConsent']=k}catch(p){window[csaName+'appSessionObject']=""}
e?window[csaName+'getSD']&&window[csaName+'getSD'](document.body,window,document,navigator):Start();return!0};window[csaName+'SC']||(window[csaName+'SC']=function(a,k,f,e,c,p,g,r){var n=document,y=window;e=a+"; path=/;";var z=a.split("=");if(y[csaName+'uSC']){if("https:"!=location.protocol)return;e+=" secure;"}
var x=e;k&&(e=e+"expires="+k);";"==e.charAt(e.length-1)&&(e=e.substring(0,e.length-1));y[csaName+'GD']&&(n.cookie=e+y[csaName+'GD']());if(r||!(-1<n.cookie.indexOf(a))||k)
if(f=location.hostname,c=f.split("."),g)n.cookie=e+";domain="+g;else{if(2<=c.length){p=c.length-2;g="."+c[p+1];do
if(g="."+c[p]+g,n.cookie=e+"; domain="+g,p--,r)try{if(-1==document.cookie.indexOf(z[0]+"="))return}catch(u){}
while((r&&-1<n.cookie.indexOf(z[0]+"=")||!r&&-1==n.cookie.indexOf(a))&&0<=p);if(!r&&-1==n.cookie.indexOf(a)&&x)
for(p=c.length-2,g="."+c[p+1];-1==n.cookie.indexOf(a)&&0<=p;)g="."+c[p]+g,n.cookie=x+" domain="+g,p--}
0!==location.href.indexOf("file://")&&(r&&-1<n.cookie.indexOf(a)||!r&&-1==n.cookie.indexOf(a))&&(r?(f=new Date,f.setFullYear(1970),n.cookie=x+" domain="+location.hostname+"; expires="+f.toGMTString()):n.cookie=x+" domain="+location.hostname);if(!r&&-1==n.cookie.indexOf(a)||r&&-1<n.cookie.indexOf(a)&&!y[csaName+'uSC']){a=a.split("=");try{var v=window.sessionStorage;k&&(v=window.localStorage);v&&(a[1]&&-1<a[1].indexOf(";")&&(a[1]=a[1].substring(0,a[1].indexOf(";"))),r?v.removeItem(a[0]):v.setItem(a[0],a[1]));return}catch(u){}
y[csaName+'SF']=1}}});window[csaName+'findCookieVal']=function(a,k){if(document.cookie)
for(var f=document.cookie.split("; "),e=0;e<f.length;e++){var c=f[e].split("=");try{if(c[0]==a)return c[1]}catch(g){}}
f="";try{var p=window.sessionStorage;if(k||csaName+"uvt"==a||csaName+"DBID"==a||csaName+"persisted"==a)p=window.localStorage;p&&(f=p.getItem(a))}catch(g){}
return f};window[csaName+'deleteLegacyCookies']=function(){var a=!0,k=window[csaName+'findCookieVal']("usy46gabsosd",!1);k&&1<k.split("::").length&&(a=!1);if(document.cookie)window[csaName+'SC']&&(a&&window[csaName+'doDeleteCookie']("usy46gabsosd"),window[csaName+'doDeleteCookie'](csaName+"uvt"),window[csaName+'doDeleteCookie'](csaName+"key"),window[csaName+'doDeleteCookie'](csaName+"DBID"));else try{window.sessionStorage&&(a&&window.sessionStorage.removeItem("usy46gabsosd"),window.sessionStorage.removeItem(csaName+"key")),window.localStorage&&(window.localStorage.removeItem(csaName+"uvt"),window.localStorage.removeItem(csaName+"DBID"))}catch(f){}};window[csaName+'doDeleteCookie']=function(a,k){var f=new Date;f.setFullYear(1970);window[csaName+'SC']&&window[csaName+'SC'](a+"=0",f.toGMTString(),"","","","",k,!0)};function sessionset(a){window[csaName+'SC'](csaName+"session="+a)}
function persisted(a,k,f,e,c,p,g,r,n,y){var z=new Date,x,v=0,u;a:{var w=document.cookie;""==w&&window.localStorage&&(w=(w=window.localStorage.getItem(csaName+"persisted"))?csaName+"persisted="+w:"");w=w.split("; ");u=0;for(var J=w.length;u<J;u++){var K=w[u].split("=");if(1<K.length&&c==K[0]){u=unescape(K[1]);break a}}
u=null}
g&&(v=g);w=!0;u&&(u=u.split("_"),7<=u.length&&(e==u[4]&&(w=!1),u[2]&&(x=u[2],r=u[3],v=u[6])));w&&(g||v++);x||(x=f);z.setTime(z.getTime()+p);y?window[csaName+'SC'](c+"="+
a+"_"+k+"_"+x+"_"+r+"_"+e+"_"+n+"_"+v,z.toGMTString()):csaName+'SC'(c+"="+a+"_"+k+"_____",z.toGMTString())}
function legacyset(a,k,f,e){var c=window,p=document.cookie;c[csaName+'GD']&&c[csaName+'GD']();var g=p.indexOf("usy46gabsosd"),r="";if(-1==g)window[csaName+'SC']&&window[csaName+'SC']("usy46gabsosd="+csaName+"__"+a+"_"+k+"_"+f+e);else{var r=p.indexOf(";",g),n=c="";0>r&&(r=p.length);p=p.substring(g+12+1,r);g=p.indexOf(csaName);-1<g?(c=p.substring(0,g),""!=c&&(c="::"+c),g=p.indexOf("::",g),-1<g&&(n=""==c?p.substring(g):p.substring(g+2))):c="::"+p;r="usy46gabsosd="+csaName+"__"+a+"_"+k+"_"+f+
e;""!=c&&(r+=c);""!=n&&(r+=n);window[csaName+'SC']&&window[csaName+'SC'](r)}}
function keyset(a,k){window[csaName+'SC'](csaName+"key="+a)}
function DBIDset(a,k){var f=new Date;f.setTime(f.getTime()+k);window[csaName+'SC'](csaName+"DBID="+a,f.toGMTString())}
function uvt(a,k,f,e,c){var p=new Date,g,r=0,n;a:{n=document.cookie;""==n&&window.localStorage&&(n=(n=window.localStorage.getItem(csaName+"uvt"))?csaName+"uvt="+n:"");n=n.split("; ");for(var y=0,z=n.length;y<z;y++){var x=n[y].split("=");if(1<x.length&&csaName+"uvt"==x[0]){n=unescape(x[1]);break a}}
n=null}
if(n&&(n=n.split("_"),5<=n.length)){if(k==n[2])return;g=n[0];e=n[1];r=n[4]}
r++;g||(g=a);p.setTime(p.getTime()+f);window[csaName+'SC'](csaName+"uvt="+g+"_"+e+"_"+k+"_"+c+"_"+r,p.toGMTString())}
function setShutdown(){window[csaName+'deleteSessionCookie']&&window[csaName+'deleteSessionCookie']();var a=(new Date).valueOf();if(window[csaName+'GD']){var k=window[csaName+'GD']();document.cookie=csaName+"SF="+a+";path=/"+k}else window[csaName+'SC']&&window[csaName+'SC'](csaName+"SF="+a)}
function Go(){try{var a=window.crypto||window.msCrypto;window[csaName+'generateUUID']=function(){return"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx".replace(/[x]/g,function(a){return(16*Math.random()|0).toString(16)})};"undefined"!=typeof a&&"undefined"!=typeof a.getRandomValues&&(window[csaName+'generateUUID']=function(){var f=new Uint16Array(8);a.getRandomValues(f);var e=function(a){for(a=a.toString(16);4>a.length;)a="0"+a;return a};return""+e(f[0])+e(f[1])+e(f[2])+e(f[3])+e(f[4])+e(f[5])+e(f[6])+
e(f[7])});window[csaName+'windowId']="_"+(new Date).getTime()+"0."+window[csaName+'generateUUID']()+"_";if(window[csaName+'AppBridgeV2']){window[csaName+'awaitingAppResponse']=!0;try{var k=window[csaName+'findCookieVal'](csaName+"persisted",!0);window[csaName+'AppBridgeV2'].requestSessionInformation(location.href,k,window[csaName+'windowId'],!0)}catch(f){window[csaName+'appSessionObject']="",window[csaName+'awaitingAppResponse']=!1,Start()}}else window[csaName+'awaitingAppResponse']=!1,Start()}catch(f){}}
Go();window[csaName+'RTEHandler']={maxWaitDurationMillis:1E4,maxActionProcessDurationMillisToAllowRequeue:50,targetMissingPollingDurationMillis:250,domContentReadyPollingDurationMillis:100,injectionCount:0,staleCount:0,rejectedCount:0,errorCount:0,nameVal:"RTEHandler",currentActionID:"",currentRuleID:"",currentContentID:"",currentCustomID:"",queue:[],isDomContentReady:function(){var a=document.getElementsByTagName("body");return a&&0!==a.length?"complete"==document.readyState||"loaded"==document.readyState||"interactive"==document.readyState?!0:!1:!1},reset:function(){this.queue=[];this.errorCount=this.rejectedCount=this.staleCount=this.injectionCount=0},getTimestampMillis:function(){return(new Date).getTime()},handleResponse:function(a,c){if(!a||!a.length||!c&&-1<document.cookie.indexOf(csaName+"SF=y"))return 0;var b=this.getTimestampMillis(),d,e,f;d=0;for(e=a.length;d<e;d++){f=a[d];try{f.queueTimestampMillis=b;if(f.content&&(f.content=this.doUnescape(f.content),f.parsedContent=this.parseContent(f.content),!f.parsedContent)){this.rejectedCount++;continue}
f.externalContentId&&(f.externalContentId=this.doUnescape(f.externalContentId));f.replacementurl&&(f.replacementurl=this.doUnescape(f.replacementurl));f.idValue&&(f.idValue=this.doUnescape(f.idValue));this.validVariables(f.csaNumber,f.contentKey)?f.csaCallbackTime?this.doCallback(f):this.queueAction(f):this.distributeActionToChildCsas(f)||this.queueAction(f)}catch(g){this.rejectedCount++,this.handleError(g)}}
return this.processQueue()},doCallback:function(a){window[csaName+'dCB']?window[csaName+'dCB'](parseInt(a.csaCallbackTime),this.getTimestampMillis()):(window[csaName+'dCBValTS']=this.getTimestampMillis(),window[csaName+'dCBVal']=parseInt(a.csaCallbackTime))},queueAction:function(a){this.queue.unshift(a)},isOlderThan:function(a,c){var b=this.getTimestampMillis();return Math.abs(b-c)>a},isActionStale:function(a){return this.isOlderThan(this.maxWaitDurationMillis,a.queueTimestampMillis)},processQueue:function(){if(0===this.queue.length)return 0;if(!this.isDomContentReady()){var a=this;window.setTimeout(function(){a.processQueue.call(a)},this.domContentReadyPollingDurationMillis);return 0}
var c=0,b;for(b=this.queue.length-1;0<=b;b--){var d=this.queue[b];try{if(this.isActionStale(d))this.staleCount++,this.queue.splice(b,1);else{var e=this.getTimestampMillis();this.processAction(d)?(this.injectionCount++,this.queue.splice(b,1),this.actionsExecutedCount++,c++):this.isOlderThan(this.maxActionProcessDurationMillisToAllowRequeue,e)&&(this.rejectedCount++,this.queue.splice(b,1))}}catch(f){this.queue.splice(b,1),this.handleError(f)}}
0<this.queue.length&&(a=this,window.setTimeout(function(){a.processQueue.call(a)},this.targetMissingPollingDurationMillis));return c},processAction:function(a){return this.validVariables(a.csaNumber,a.contentKey)?(this.currentActionID=a.actionID,this.currentRuleID=a.ruleID,this.currentContentID=a.contentID,this.currentCustomID=a.customID,a=this.updateContent(a),this.currentCustomID=this.currentContentID=this.currentRuleID=this.currentActionID="",a):this.distributeActionToChildCsas(a)},validVariables:function(a,c){return window[csaName+'wid']!=a||c&&c!=window[csaName+'contentKey']?!1:!0},isObjectInArray:function(a,c){if(!c||!a)return!1;for(var b=0,d=c.length;b<d;b++)
if(c[b]===a)return!0;return!1},recurseChildCsas:function(a,c,b){var d=-1;try{d=a[csaName+'wid']}catch(f){return!1}
if(d==c.csaNumber){if(a[csaName+'RTEHandler'])return c.csaCallbackTime&&a[csaName+'RTEHandler'].doCallback(c),a[csaName+'RTEHandler'].queueAction(c),this.isObjectInArray(a,b)||b.push(a),!0}else try{if(a.frames&&0<a.frames.length)
for(var d=0,e=a.frames.length;d<e;d++)
if(this.recurseChildCsas(a.frames[d],c,b))return!0}catch(f){}
return!1},distributeActionToChildCsas:function(a){if(window[csaName+'gHW']){var c=[];a=this.recurseChildCsas(window[csaName+'gHW'](),a,c);if(0<c.length)
for(var b=0,d=c.length;b<d;b++)c[b][csaName+'RTEHandler'].processQueue();return a}
return!1},insertNodeAfter:function(a,c){var b=c.parentNode;b.lastchild==c?b.appendChild(a):b.insertBefore(a,c.nextSibling)},getParentElement:function(a){return a.parentElement?a.parentElement:a.parentNode?a.parentNode:""},replaceImage:function(a,c,b){if(b){for(var d=!1,e=a;a&&!d;){if(a.href&&("a"==(""+a.tagName).toLowerCase()||"area"==(""+a.tagName).toLowerCase())){a.href=b;d=!0;break}
var f=this.getParentElement(a);if(a===f)break;a=f}
if(d)e.src=c;else if(a=document.createElement("SPAN"),d=document.createElement("A"),d.href=b,a.appendChild(d),b=this.getParentElement(e))b.replaceChild(a,e),d.appendChild(e),e.src=c,e.setAttribute("style","border-style: none")}else a.src=c},doUnescape:function(a){window.decodeURIComponent||(a=a.replace(/%C2%A3/g,"%A3"));a=a.replace(/\\+/g,"%20");return a=window.decodeURIComponent?window.decodeURIComponent(a):unescape(a)},pushContentAddedData:function(a){this.currentActionID&&(window[csaName+'variableStateChange']?window[csaName+'reportContentAction'](this.currentActionID,this.currentRuleID,this.currentContentID,this.currentCustomID):(window[csaName+'ContentIdArray']||(window[csaName+'ContentIdArray']=[]),window[csaName+'ContentIdArray'][window[csaName+'ContentIdArray'].length]={actionId:this.currentActionID,ruleId:this.currentRuleID,contentId:this.currentContentID,customId:this.currentCustomID}))},getFormName:function(a){if(!a)return"";var c=a.getAttribute("name");return c?c:a.name&&!a.name.type?a.name:""},getFormID:function(a){if(!a)return"";var c=a.getAttribute("id");return c?c:a.id&&!a.id.type?a.id:""},getElementClass:function(a){var c=a.getAttribute("class");c||(c=a.getAttribute("className"));return c},findMatchesByParentFormName:function(a,c,b){var d=new RegExp(c);a||(a=document.getElementsByTagName("*"));for(var e=[],f=0,g=a.length;f<g;f++)
if(a[f].form){var h=this.getFormName(a[f].form);b?d.test(h)&&(e[e.length]=a[f]):c==h&&(e[e.length]=a[f])}return e},findMatchesByParentFormID:function(a,c,b){var d=new RegExp(c);a||(a=document.getElementsByTagName("*"));for(var e=[],f=0,g=a.length;f<g;f++)
if(a[f].form){var h=this.getFormID(a[f].form);b?d.test(h)&&(e[e.length]=a[f]):c==h&&(e[e.length]=a[f])}return e},findMatchesByName:function(a,c,b){a||(a=document.getElementsByTagName("*"));var d=[];if(b)
for(c=new RegExp(c),b=0;b<a.length;b++)c.test(a[b].name)&&(d[d.length]=a[b]);else
for(c=c?c.toLowerCase():c,b=0;b<a.length;b++){var e=(""+a[b].name).toLowerCase();c==e&&(d[d.length]=a[b])}
return d},findMatchesById:function(a,c,b){a||(a=document.getElementsByTagName("*"));var d=[];if(b)
for(c=new RegExp(c),b=0;b<a.length;b++)c.test(a[b].id)&&(d[d.length]=a[b]);else
for(b=0;b<a.length;b++)c==a[b].id&&(d[d.length]=a[b]);return d},findMatchesByClass:function(a,c,b){a||(a=document.getElementsByTagName("*"));var d=[];if(b)
for(c=new RegExp(c),b=0;b<a.length;b++)c.test(this.getElementClass(a[b]))&&(d[d.length]=a[b]);else
for(b=0;b<a.length;b++)c==this.getElementClass(a[b])&&(d[d.length]=a[b]);return d},findMatchesByHref:function(a,c,b){a||(a=document.getElementsByTagName("A"));var d=[];if(b)
for(c=new RegExp(c),b=0;b<a.length;b++)c.test(a[b].href)&&(d[d.length]=a[b]);else
for(c=c.toLowerCase(),b=0;b<a.length;b++){var e=(""+a[b].href).toLowerCase();c==e&&(d[d.length]=a[b])}
return d},findMatchesBySrc:function(a,c,b){a||(a=document.getElementsByTagName("IMG"));var d=[];if(b)
for(c=new RegExp(c),b=0;b<a.length;b++)c.test(a[b].src)&&(d[d.length]=a[b]);else
for(c=c.toLowerCase(),b=0;b<a.length;b++){var e=(""+a[b].src).toLowerCase();c==e&&(d[d.length]=a[b])}
return d},findMatchesByTagName:function(a,c,b){c=c.toUpperCase();a||(a=document.getElementsByTagName("*"));var d=[];if(b)
for(c=new RegExp(c),b=0;b<a.length;b++)c.test((""+a[b].tagName).toUpperCase())&&(d[d.length]=a[b]);else
for(b=0;b<a.length;b++){var e=(""+
a[b].tagName).toUpperCase();c==e&&(d[d.length]=a[b])}
return d},findMatchesByType:function(a,c,b){c=c.toLowerCase();a||(a=document.getElementsByTagName("*"));var d=[];if(b)
for(c=new RegExp(c),b=0;b<a.length;b++)c.test((""+a[b].type).toLowerCase())&&(d[d.length]=a[b]);else
for(b=0;b<a.length;b++){var e=(""+a[b].type).toLowerCase();c==e&&(d[d.length]=a[b])}
return d},updateContent:function(a){"undefined"!=typeof SpeedTrapComponent&&SpeedTrapComponent.logMessage("Inserting "+a.parsedContent);if(3==a.csaAction)return this.insertContentAtTopOfPage(a.parsedContent),!0;if(4==a.csaAction)return this.insertContentAtEndOfPage(a.parsedContent),!0;if(!a.attributesArray)return!1;for(var c=!1,b=null,d="",e="",f="",g="",h="",p="",k=0,q=a.attributesArray.length;k<q;k++){var l=a.attributesArray[k].attributeType,m=a.attributesArray[k].attributeValue,n=a.attributesArray[k].attributeIsRegEx;"NAME"==l?b=this.findMatchesByName(b,m,n):"ID"==l?b=this.findMatchesById(b,m,n):"CLASS"==l?b=this.findMatchesByClass(b,m,n):"IMAGE"==l?(d={val:m,isRegex:n},c=!0):"ANCHOR"==l?e={val:m,isRegex:n}:"TAGNAME"==l?f={val:m,isRegex:n}:"FORM_NAME"==l?g={val:m,isRegex:n}:"FORM_ID"==l?h={val:m,isRegex:n}:"TYPE"==l&&(p={val:m,isRegex:n})}
g&&(b=this.findMatchesByParentFormName(b,g.val,g.isRegex));h&&(b=this.findMatchesByParentFormID(b,h.val,h.isRegex));e&&(b=this.findMatchesByHref(b,e.val,e.isRegex));d&&(b=this.findMatchesBySrc(b,d.val,d.isRegex));f&&(b=this.findMatchesByTagName(b,f.val,f.isRegex));p&&(b=this.findMatchesByType(b,p.val,p.isRegex));if(null===b)return!1;e=!1;for(k=0;k<b.length;k++)d=b[k],f=(""+b[k].tagName).toUpperCase(),"HEAD"!=f&&"META"!=f&&(c&&"IMAGE"==a.replacementContentType?(0==a.csaAction?(this.replaceImage(d,a.parsedContent.childNodes[0].nodeValue,a.replacementurl),this.tagContent(d)):1==a.csaAction?(e=this.toInnerHtmlNode(a.parsedContent.childNodes[0]),(f=d.parentNode)&&f.insertBefore(e,d)):2==a.csaAction&&(e=this.toInnerHtmlNode(a.parsedContent.childNodes[0]),this.insertNodeAfter(e,d)),e=!0):(e=!0,this.modifyTarget(d,a)),this.pushContentAddedData());return e},insertContentAtTopOfPage:function(a){var c=document.createElement("SPAN");this.tagContent(c);var b=document.getElementsByTagName("body")[0];b&&(b.insertBefore(c,b.firstChild),this.appendToDoc(c,a),this.pushContentAddedData())},insertContentAtEndOfPage:function(a){var c=document.createElement("SPAN");this.tagContent(c);var b=document.getElementsByTagName("body")[0];b&&(b.appendChild(c),this.appendToDoc(c,a),this.pushContentAddedData())},modifyTarget:function(a,c){if(a){var b=document.createElement("SPAN");this.tagContent(b);var d=a.parentNode;0==c.csaAction?d&&d.replaceChild(b,a):1==c.csaAction?d&&d.insertBefore(b,a):2==c.csaAction&&this.insertNodeAfter(b,a);this.appendToDoc(b,c.parsedContent)}},parseContent:function(a){if(window.DOMParser)a=(new DOMParser).parseFromString(a,"text/xml");else{var c=new ActiveXObject("Microsoft.XMLDOM");c.async="false";c.loadXML(a);a=c}
a=a.getElementsByTagName("strtecontent");return 1==a.length?a[0]:null},getHeadReference:function(){var a=document.getElementsByTagName("HEAD");return 0<a.length?a[0]:null},appendToDoc:function(a,c){var b=null,d=c.nodeName.toUpperCase();if("STRTECONTENT"==d)b=a;else if("HEAD"==d){var e=this.getHeadReference();if(e){for(d=0;d<c.childNodes.length;d++)this.appendToDoc(e,c.childNodes[d]);return}}else if(b=this.createNewNode(c,a),null===b)return;e=0===d.indexOf("FB");if("SCRIPT"!=d&&"NOSCRIPT"!=d&&"STYLE"!=d&&"OBJECT"!=d&&"TABLE"!=d&&"H1"!=d&&"H2"!=d&&"H3"!=d&&"H4"!=d&&"H5"!=d&&"H6"!=d&&!e)
for(d=0;d<c.childNodes.length;d++)this.appendToDoc(b,c.childNodes[d])},createNewNode:function(a,c){var b;if(3==a.nodeType)b=document.createTextNode(a.nodeValue),c.appendChild(b);else{if(1==a.nodeType){b=a.nodeName.toUpperCase();var d=0===b.indexOf("FB");"OBJECT"==b||"TABLE"==b||"H1"==b||"H2"==b||"H3"==b||"H4"==b||"H5"==b||"H6"==b||d?(b=this.createObjectNode(a),c.appendChild(b)):"SCRIPT"==b?b=this.createScriptNode(a,c):"NOSCRIPT"==b?(b=this.createNoScriptNode(a),c.appendChild(b)):"STYLE"==b?b=this.createStyleNode(a,c):(b=document.createElement(a.nodeName.toUpperCase()),this.copyAttributes(a,b),c.appendChild(b));return b}
return null}},createObjectNode:function(a){return this.toInnerHtmlNode(a)},tagInjectedContent:function(a,c,b,d,e){a&&(c&&(a[csaName+'contentActionIdentifier']=c),b&&(a[csaName+'ruleIdentifier']=b),d&&(a[csaName+'contentIdentifier']=d),e&&(a[csaName+'customIdentifier']=e))},tagContent:function(a){this.tagInjectedContent(a,this.currentActionID,this.currentRuleID,this.currentContentID,this.currentCustomID)},toXML:function(a){return"undefined"!=typeof XMLSerializer?(new XMLSerializer).serializeToString(a):a.xml?a.xml:""},toInnerHtmlNode:function(a){var c=document.createElement("SPAN");c.innerHTML=this.toXML(a);this.tagContent(c);return c},createScriptNode:function(a,c){var b=document.createElement("SCRIPT");c.appendChild(b);var d=a.attributes.getNamedItem("type");d&&(b.type=d.value);if(d=a.attributes.getNamedItem("src"))b.src=d.value;0<a.childNodes.length&&(b.text=a.childNodes[0].nodeValue);return b},createNoScriptNode:function(a){for(var c=document.createElement("NOSCRIPT"),b=document.createElement("SPAN"),d=0;d<a.childNodes.length;d++)this.appendToDoc(b,a.childNodes[d]);c.text=b.innerHTML;return c},createStyleNode:function(a,c){var b=document.createElement("STYLE");c.appendChild(b);var d=a.attributes.getNamedItem("type");d&&(b.type=d.value);if(d=a.attributes.getNamedItem("src"))b.src=d.value;if(d=a.attributes.getNamedItem("media"))b.media=d.value;0<a.childNodes.length&&(b.styleSheet?b.styleSheet.cssText=a.childNodes[0].nodeValue:b.innerHTML=this.toXML(a.childNodes[0]));return b},copyAttributes:function(a,c){for(var b=null,d=null,e=0,f=a.attributes.length;e<f;e++){var g=""+a.attributes[e].name,h=a.attributes[e].value;if("style"==g.toLowerCase())c.style.cssText=h;else if("class"==g.toLowerCase())window.attachEvent?c.className=h:c.setAttribute(g,h);else if("type"==g){b=h;continue}
"value"==g?d=h:c.setAttribute(g,h)}
b&&c.setAttribute("type",b);d&&(c.setAttribute("value",d),c.value=d)},handleError:function(a){this.errorCount++;if(window.SpeedTrapComponent){var c;c="There was an error.\n"+("Error description: "+
a.message+"\n");c+="Line no: "+a.lineNumber+"\n";a.stack&&(c+="Stack: "+a.stack);window.SpeedTrapComponent.logMessage("Error "+c)}}};;}
u.counter=u.counter||1;(function(u){var delay=u.data.celebrus_spa_counter_delay||2;u.counter+=1;function setBrowserUrl(s){if(window.utag.data){window.utag.data['vendor_celebrus_prev_url']=encodeURIComponent(s);}}
function browserUrlTrigger(u,b){if(u.data.doReinit_url_fire.toString()==="1"){if(encodeURIComponent(window.location.href)!==window.utag.data['vendor_celebrus_prev_url'].toString()){window[csaName+'doReInit']();console.log('matched')}}else{window[csaName+'doReInit']();}}
if(utag_cfg_ovrd.noview==true&&b["ut.event"]=="view"&&u.data.doReinit_collection.toString()==="1"&&u.counter>delay){browserUrlTrigger(u,b);}
if(utag_cfg_ovrd.noview==true&&b["ut.event"]=="view"&&u.data.doReinit_collection.toString()==="1"){setBrowserUrl(window.location.href);}
return u;})(u);(function(u,b){if(u.data.udo_collection.toString()=="1"){window[csaName+'SendJsonData']({events:[mergeUDOs(u.map,u.data)]});}})(u,b)
utag.DB("send:314:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("314","hsbc.ar-rbwm"));}catch(error){utag.DB(error);}
